# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: casaos-app-management
before:
  hooks:
    - go generate
    - go run github.com/google/go-licenses@latest check . --disallowed_types=restricted
    - go mod tidy
    - go test -race -v ./... -timeout 30m
builds:
  - id: casaos-app-management-amd64
    binary: build/sysroot/usr/bin/casaos-app-management
    hooks:
      post:
        - cmd: go build -v -tags 'musl netgo osusergo' -o build/sysroot/usr/bin/appfile2compose github.com/IceWhaleTech/CasaOS-AppManagement/cmd/appfile2compose
          output: true
        - cmd: upx --best --lzma -v --no-progress build/sysroot/usr/bin/appfile2compose
          output: true
        - cmd: upx --best --lzma -v --no-progress "{{ .Path }}"
          output: true
    env:
      - CC=x86_64-linux-gnu-gcc
    ldflags:
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -s
      - -w
      - -extldflags "-static"
    tags:
      - musl
      - netgo
      - osusergo
    goos:
      - linux
    goarch:
      - amd64
  - id: casaos-app-management-arm64
    binary: build/sysroot/usr/bin/casaos-app-management
    hooks:
      post:
        - cmd: go build -v -tags 'musl netgo osusergo' -o build/sysroot/usr/bin/appfile2compose github.com/IceWhaleTech/CasaOS-AppManagement/cmd/appfile2compose
          output: true
        # - cmd: upx --best --lzma -v --no-progress build/sysroot/usr/bin/appfile2compose
        #   output: true
        # - cmd: upx --best --lzma -v --no-progress "{{ .Path }}"
        #   output: true
    env:
      - CC=aarch64-linux-gnu-gcc
    ldflags:
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -s
      - -w
      - -extldflags "-static"
    tags:
      - musl
      - netgo
      - osusergo
    goos:
      - linux
    goarch:
      - arm64
  - id: casaos-app-management-arm-7
    binary: build/sysroot/usr/bin/casaos-app-management
    hooks:
      post:
        - cmd: go build -v -tags 'musl netgo osusergo' -o build/sysroot/usr/bin/appfile2compose github.com/IceWhaleTech/CasaOS-AppManagement/cmd/appfile2compose
          output: true
        - cmd: upx --best --lzma -v --no-progress build/sysroot/usr/bin/appfile2compose
          output: true
        - cmd: upx --best --lzma -v --no-progress "{{ .Path }}"
          output: true
    env:
      - CC=arm-linux-gnueabihf-gcc
    ldflags:
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -s
      - -w
      - -extldflags "-static"
    tags:
      - musl
      - netgo
      - osusergo
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - "7"
  - id: casaos-app-management-migration-tool-amd64
    binary: build/sysroot/usr/bin/casaos-app-management-migration-tool
    hooks:
      post:
        - upx --best --lzma -v --no-progress "{{ .Path }}"
    main: ./cmd/migration-tool
    env:
      - CC=x86_64-linux-gnu-gcc
    ldflags:
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -s
      - -w
      - -extldflags "-static"
    tags:
      - musl
      - netgo
      - osusergo
    goos:
      - linux
    goarch:
      - amd64
  - id: casaos-app-management-migration-tool-arm64
    binary: build/sysroot/usr/bin/casaos-app-management-migration-tool
    # hooks:
    #   post:
    #     - upx --best --lzma -v --no-progress "{{ .Path }}"
    main: ./cmd/migration-tool
    env:
      - CC=aarch64-linux-gnu-gcc
    ldflags:
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -s
      - -w
      - -extldflags "-static"
    tags:
      - musl
      - netgo
      - osusergo
    goos:
      - linux
    goarch:
      - arm64
  - id: casaos-app-management-migration-tool-arm-7
    binary: build/sysroot/usr/bin/casaos-app-management-migration-tool
    hooks:
      post:
        - upx --best --lzma -v --no-progress "{{ .Path }}"
    main: ./cmd/migration-tool
    env:
      - CC=arm-linux-gnueabihf-gcc
    ldflags:
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -s
      - -w
      - -extldflags "-static"
    tags:
      - musl
      - netgo
      - osusergo
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - "7"
  - id: casaos-app-management-validator-amd64
    binary: build/sysroot/usr/bin/casaos-app-management-validator
    hooks:
      post:
        - upx --best --lzma -v --no-progress "{{ .Path }}"
    main: ./cmd/validator
    env:
      - CC=x86_64-linux-gnu-gcc
    ldflags:
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -s
      - -w
      - -extldflags "-static"
    tags:
      - musl
      - netgo
      - osusergo
    goos:
      - linux
    goarch:
      - amd64

archives:
  - name_template: >-
      {{ .Os }}-{{- if eq .Arch "arm" }}arm-7{{- else }}{{ .Arch }}{{- end }}-{{ .ProjectName }}-v{{ .Version }}
    id: casaos-app-management
    builds:
      - casaos-app-management-amd64
      - casaos-app-management-arm64
      - casaos-app-management-arm-7
    files:
      - build/**/*
  - name_template: >-
      {{ .Os }}-{{- if eq .Arch "arm" }}arm-7{{- else }}{{ .Arch }}{{- end }}-{{ .ProjectName }}-migration-tool-v{{ .Version }}
    id: casaos-app-management-migration-tool
    builds:
      - casaos-app-management-migration-tool-amd64
      - casaos-app-management-migration-tool-arm64
      - casaos-app-management-migration-tool-arm-7
    files:
      - build/sysroot/etc/**/*
  - name_template: >-
      {{ .Os }}-{{- if eq .Arch "arm" }}arm-7{{- else }}{{ .Arch }}{{- end }}-{{ .ProjectName }}-validator-v{{ .Version }}
    id: casaos-app-management-validator
    builds:
      - casaos-app-management-validator-amd64
    files:
      - build/sysroot/etc/**/*

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  github:
    owner: IceWhaleTech
    name: CasaOS-AppManagement
  draft: false
  prerelease: auto
  mode: replace
  name_template: "v{{ .Version }}"
